service: ccg

plugins:
  - serverless-dynamodb-local
  - serverless-python-requirements
  - serverless-stack-output
  - serverless-offline

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
  output:
    file: stack.yml
  pythonRequirements:
    dockerizePip: non-linux
  serverless-offline:
    httpPort: 5001

package:
  individually: false
  include:
    - './backend/**'
  exclude:
    - '**'

provider:
  environment:
    APP_ENDPOINT: http://ccg-dev-frontend.s3-website-us-east-1.amazonaws.com
    DYNAMODB_TABLE: !Ref dynamodbTable
    SHOPIFY_API_KEY: 5d9c7da289fe90dcde12d6cdc8cf3a45
    SHOPIFY_API_SECRET: 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
    SHOPIFY_API_VERSION: 2020-10
  httpApi:
    cors: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:*
      Resource: "*"
  name: aws
  profile: personal
  region: us-east-1
  runtime: python3.8
  stage: ${opt:stage, "dev"}

functions:
  get_permission_url:
    handler: backend/endpoints/install.get_permission_url
    events:
      - httpApi:
          path: /get_permission_url
          method: GET
  app_installed:
    handler: backend/endpoints/install.app_installed
    events:
      - httpApi:
          path: /app_installed
          method: GET
  app_uninstalled:
    handler: backend/endpoints/install.app_uninstalled
    events:
      - httpApi:
          path: /app_uninstalled
          method: GET

  get_templates:
    handler: backend/endpoints/templates.get_templates
    events:
      - httpApi:
          path: /get_templates
          method: GET
  create_template:
    handler: backend/endpoints/templates.create_template
    events:
      - httpApi:
          path: /create_template
          method: POST
  delete_template:
    handler: backend/endpoints/templates.delete_template
    events:
      - httpApi:
          path: /delete_template
          method: GET

resources:
  Resources:
    dynamodbTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ccg
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: resource_id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: resource_id
            AttributeType: S

    s3FrontendBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:service}-${self:provider.stage}-frontend
        LoggingConfiguration:
          DestinationBucketName: !Ref s3FrontendAccessLogsBucket
          LogFilePrefix: ${self:service}-access-logs
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
    s3FrontendAccessLogsBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: LogDeliveryWrite
        BucketName: ${self:service}-${self:provider.stage}-frontend-access-logs

  Outputs:
    dynamodbTableName:
      Value: !Ref dynamodbTable
      Description: DynamoDB Table`
    s3FrontendBucketWebsiteURL:
      Value: !GetAtt [ s3FrontendBucket, WebsiteURL ]
      Description: URL for the frontend website hosted on S3
    s3FrontendAccessLogsBucketName:
      Value: !Ref s3FrontendAccessLogsBucket
      Description: Frontend access logs bucket name
