cloudfrontFrontendDistributionName: EAU28P9LJQ1MT
CreateUnderscoretemplateLambdaFunctionQualifiedArn: 'arn:aws:lambda:us-east-1:637649536396:function:ccg-dev-create_template:2'
CreateUnderscoreshopLambdaFunctionQualifiedArn: 'arn:aws:lambda:us-east-1:637649536396:function:ccg-dev-create_shop:2'
HttpApiId: 8bg2fa9sl6
ServerlessDeploymentBucketName: ccg-dev-serverlessdeploymentbucket-oty3r6gohql9
HttpApiUrl: 'https://8bg2fa9sl6.execute-api.us-east-1.amazonaws.com'
GetUnderscoretemplatesLambdaFunctionQualifiedArn: 'arn:aws:lambda:us-east-1:637649536396:function:ccg-dev-get_templates:2'
GetUnderscoreaccessUnderscoretokenLambdaFunctionQualifiedArn: 'arn:aws:lambda:us-east-1:637649536396:function:ccg-dev-get_access_token:2'
GetUnderscoreshopLambdaFunctionQualifiedArn: 'arn:aws:lambda:us-east-1:637649536396:function:ccg-dev-get_shop:2'
UpdateUnderscoreshopLambdaFunctionQualifiedArn: 'arn:aws:lambda:us-east-1:637649536396:function:ccg-dev-update_shop:2'
dynamodbTableName: ccg
cloudfrontFrontendOriginAccessIdentityName: E4W5BTKLHRL3P
cloudfrontFrontendDistributionURL: 'https://d34atibz1s1rfh.cloudfront.net'
